### ISSUE TITLE
clean your code

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#10]
clean your code, found 8 issues

also,  `/n` is `\n` !!! (this is not one of them)

**Comment by marriog** [comment]
noted, updated and pushed

**Comment by marriog** [comment]
actually only saw 6 mistakes 4 /n and 3 white spaces. i must be missing some.
updated and pushed

**Comment by zupa-hu** [comment]
maybe you made some new once go through it again.

**Comment by zupa-hu** [comment]
sorry I seem to be bad with buttons :D

**Comment by marriog** [comment]
:D not as bas as me with the \n char!
diff link:
4e941f7

**Comment by zupa-hu** [comment]
Gav, your Between.go is beautifully amazing. Thanks for sharing that joy with me.

**Comment by zupa-hu** [comment]
But Between_test.go is freekin' ugly.

Also, don't write
`if actual != expected || found == false {`
instead use parenthesis as in
`if (actual != expected) || (found == false) {`

For clarity, and to take on the habit, programming languages may define operator precedence slightly differently, avoid the risk. Also, it is faster to read.

**Comment by zupa-hu** [comment]
Also, simplify, don't even have them in one line.

```go
if ! found {
    t.Fatal(...)
}
if actual != expected {
    t.Fatal(...)
}
``

**Comment by zupa-hu** [comment]
`foundFunction` -> why not call it `found` ?

**Comment by zupa-hu** [comment]
why does foundFunction return a bool when it is not used anywhere?
If only for being able to call `return`, you can as well call `return` without arguments.

**Comment by zupa-hu** [comment]
ugly
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L23
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L24
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L25

not very useful
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L26

even less useful
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L27

**Comment by marriog** [comment]
diff link for all these points : 1585e20

why does foundFunction return a bool when it is not used anywhere?
 - removed in this reply's diff link

foundFunction -> why not call it found ?
 - updated in this same diff link


not very useful
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L26
 - updated in this same diff link
even less useful
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L27
 - updated in this same diff link


{
ugly
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L23
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L24
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L25
}
 - you mean the words used or the spaces used?

**Comment by zupa-hu** [comment]
here you don't have a newline
https://github.com/marriog/learning/blob/1585e20812795eb8ea3bc9b28e5f3243c2589902/strings/Between_test.go#L27

here you do have
https://github.com/marriog/learning/blob/1585e20812795eb8ea3bc9b28e5f3243c2589902/strings/Between_test.go#L44

That is inconsistent. You should either have both or none. I'd suggest that for clarity, you remove newlines
https://github.com/marriog/learning/blob/1585e20812795eb8ea3bc9b28e5f3243c2589902/strings/Between_test.go#L18
https://github.com/marriog/learning/blob/1585e20812795eb8ea3bc9b28e5f3243c2589902/strings/Between_test.go#L37
https://github.com/marriog/learning/blob/1585e20812795eb8ea3bc9b28e5f3243c2589902/strings/Between_test.go#L44

because than visually you clearly have 2 paragraphs. But that is a very opinionated point I let you decide that.

**Comment by zupa-hu** [comment]
btw it looks much nicer

**Comment by marriog** [comment]
updated, here is the new update 32e06bc

**Comment by zupa-hu** [comment]
okay, now it is consistent, but you remove the newline between the paragraphs as well
https://github.com/marriog/learning/blob/32e06bcf3ec1829953ca9b3fd43c335e21067f05/strings/Between_test.go#L30

also, at the top, you have [func, test-data, for-loop], at the bottom you have [test-data, func, for-loop].

The top and bottom part are two separate logical parts that's why they should be separated by a new-line to treat them as different paragraphs.

Do you see why that matters?

**Comment by zupa-hu** [comment]
You get me worried with this. You didn't structure your code before and I feel like you have no drive to do it. Are you just doing what I tell you to do or do you actually understand the motivation behind it?

**Comment by marriog** [comment]
yes i am really motivated. i thought i can format it as i wish, as long as it is consistent.
In this case i removed all new lines to be consistent. i thought about putting one new line between the two test cases then decided against it. So now i'm thinking only new lines before new paragraphs (defined by functionality -i.e. new test case)

**Comment by zupa-hu** [comment]
The point of new lines is to help visualize the structure of the code, just like the point of indentation.
Consistency is an orthogonal topic, by removing all new-lines you pass that test.

By inserting a single newline between the found and not found test cases you slightly separate the 2 blocks thus you make it visually easier to understand the structure in the code.

```go
{
	found :=  func(s1, from, to, expected string) {
		actual, found := Between(s1, from, to)
		if actual != expected || found == false {
			t.Fatalf("expected [%v] but got [%v] Found was:[%v]\n input was [%s]\n", expected, actual, found, s1)
		} 		
	}
	foundData := []testData{
		{"here is an example where the to is left blank", "to", "", " is left blank"},
		{"this is a sandwich", "this", "sandwich", " is a "},
		{"bread meat bread", "bread", "bread", " meat "},
		{"this is a paragraph\n with new lines and tabs in, here is a tab[	]\nthis is the last line in the paragraph", ",", "t", " here is a "},
		{"this is a paragraph\n with new lines and tabs in, here is a tab[	]\nthis is the last line in the paragraph", ",", "t", " here is a "},
		{`<img src="http://google.com/image1.png">image link</image1	age>`, `src="`, `"`, "http://google.com/image1.png"},
	}
	for _, v := range foundData {
		found(v.s1, v.from, v.to, v.expected)
	}

	notFoundData := []testData{
		{"this is a sandwich", "hiddentoken", "sandwich", ""},
		{"__12345__", "__", "_2_2_2", ""},
		{"this is a paragraph\n with new lines and tabs in here is a tab[	]\nthis is the last line in the paragraph", "", "", ""},
		{"this is a paragraph\n with new lines and tabs in here is a tab[	]\nthis is the last line in the paragraph", "", "", ""},
	}
	notFound :=  func(s1, from, to, expected string) {
		actual, found := Between(s1, from, to)
		if actual != expected || found == true {
			t.Fatalf("expected [%v] but got [%v] Found was:[%v]\n input was [%s]\n", expected, actual, found, s1)
		} 		
	}
	for _, v := range notFoundData {
		notFound(v.s1, v.from, v.to, v.expected)
	}
}
```

**Comment by zupa-hu** [comment]
You could of course establish that grouping other ways, like this

```go
func TestBetween_found(t *testing.T) {
	found :=  func(s1, from, to, expected string) {
		actual, found := Between(s1, from, to)
		if actual != expected || found == false {
			t.Fatalf("expected [%v] but got [%v] Found was:[%v]\n input was [%s]\n", expected, actual, found, s1)
		} 		
	}
	foundData := []testData{
		{"here is an example where the to is left blank", "to", "", " is left blank"},
		{"this is a sandwich", "this", "sandwich", " is a "},
		{"bread meat bread", "bread", "bread", " meat "},
		{"this is a paragraph\n with new lines and tabs in, here is a tab[	]\nthis is the last line in the paragraph", ",", "t", " here is a "},
		{"this is a paragraph\n with new lines and tabs in, here is a tab[	]\nthis is the last line in the paragraph", ",", "t", " here is a "},
		{`<img src="http://google.com/image1.png">image link</image1	age>`, `src="`, `"`, "http://google.com/image1.png"},
	}
	for _, v := range foundData {
		found(v.s1, v.from, v.to, v.expected)
	}
}
func TestBetween_notFound(t *testing.T) {
	notFoundData := []testData{
		{"this is a sandwich", "hiddentoken", "sandwich", ""},
		{"__12345__", "__", "_2_2_2", ""},
		{"this is a paragraph\n with new lines and tabs in here is a tab[	]\nthis is the last line in the paragraph", "", "", ""},
		{"this is a paragraph\n with new lines and tabs in here is a tab[	]\nthis is the last line in the paragraph", "", "", ""},
	}
	notFound :=  func(s1, from, to, expected string) {
		actual, found := Between(s1, from, to)
		if actual != expected || found == true {
			t.Fatalf("expected [%v] but got [%v] Found was:[%v]\n input was [%s]\n", expected, actual, found, s1)
		} 		
	}
	for _, v := range notFoundData {
		notFound(v.s1, v.from, v.to, v.expected)
	}
}
```

..but it may be too much writing for to little gain.

ps - I use the underscore explicitly to separate the func name from some sort of a tag behind it, because I ran into cases where I later needed to test a func named like BetweenFound() and then there was a naming conflict with the test func name TestBetweenFound().

**Comment by zupa-hu** [comment]
@"yes i am really motivated"
I didn't question that, I asked if you understand the motivation behind the code structuring.

**Comment by marriog** [comment]
ok @ understood the space inbetween the two test units. 
to confirm i understand the '_' situation are you saying...
"always use underscore chars in test functions that have more than one word?
i.e. i should always use:
TestBetween_notFound
not
TestBetweenNotFound
?

**Comment by marriog** [comment]
@"Consistency is an orthogonal topic"
 - you are also teaching me new words! "orthogonal" :)

**Comment by zupa-hu** [comment]
@TestBetween_notFound, I think the takeaway should be that rules like CamelCase naming should be guidelines and don't follow rules blindly. It's fine to break any rule as long as you know why.

I use TestBetween_notFound with underscore so that it's more clear which part is the name of the function and which is only part of the test func name. This is very opiniated you don't need to follow it. 99% of the time it is no issue anyway, you won't likely have a func BetweenNotFound().

**Comment by zupa-hu** [comment]
as for the space between paragraphs, it's not used either in master or in Mutlibyte-testing. Do you intentd do use it are do you intentionally don't?

https://github.com/marriog/learning/blob/master/strings/Between_test.go
https://github.com/marriog/learning/blob/Mutlibyte-testing/strings/Between_test.go

Please sort this out I really don't want to block you for a year on func 1/50.

**Comment by marriog** [comment]
Sorry, I noticed that the master branch was not well formatted.
I decided to use a new line to separate the two paragraphs consistently.
For your reference both branches are here:
https://github.com/marriog/learning/blob/ca2b48d4d07639a5a826dcc61321c9a4067652d3/strings/Between_test.go#L28

https://github.com/marriog/learning/blob/f259c859e31924842f456e528ac64b1113087a30/strings/Between_test.go#L28

**Comment by zupa-hu** [comment]
thx
