### ISSUE TITLE
Reduce code depth

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#12]
Reduce code depth, turn this
```go
if A {
	if B {
		if C {
			return true
		} else {
			return false
		}
	} else {
		return false
	}
} else {
	return false
}
```

into this:
```go
if ! A {
	return false
}

if ! B {
	return false
}

if ! C {
	return false
}

return true
```

This applies to your Between function. Always strive to reduce code depth as deep code is more complex.

**Comment by marriog** [comment]
wicked! another nugget for great programming. i may i do same again a few times, but i will try to remove depth as much as possible.

**Comment by zupa-hu** [comment]
You only implemented it partially. You have a `return "", false` at the end in an else case. Return errors and "not-founds" and the like as soon as you can so that your main thing happens in non-nested code, like your return sandwich now.

**Comment by marriog** [comment]
updated

**Comment by zupa-hu** [comment]
again, you haven't pushed and also you haven't given me a commit reference.

Gav, hello?

**Comment by marriog** [comment]
i am confused with this thread sorry.
Here is the diff link for removing the
return "", false
line

https://github.com/marriog/learning/commit/d2658f0777cbcbb105b39e0a431bcb18fc90d9a7

**Comment by zupa-hu** [comment]
Instead of this

```go
if -1 < startOfTo {
	result = sandwhich[:startOfTo]
	return result, true
} else{
	return "", false
}
```

Use this form:
```go
if startOfTo <= -1 {
	return "", false
}

result = sandwhich[:startOfTo]
return result, true
```

It returns false/error case sooner, leaving the main program flow in, well, the main flow :D
So it is not hidden in an if branch. The non-burried way is the highway of your program, keep it the main road.

**Comment by marriog** [comment]
0aebfe9
noted and i have updated the ==-1 to <=-1

**Comment by zupa-hu** [comment]
You missed the point. == -1 is fine as strings.Index is defined to return -1 if not found. It's just my way of writing it  The point was to move the `return "", false` in the if statement and the `return result, true` out of it

**Comment by marriog** [comment]
ok, i understand now. so i should try to leave the real answer of the function for the end (the main road)/final return, rather than buried in an if statement?
11433f9

**Comment by zupa-hu** [comment]
Yup. Jeez you added the new line at the end again.

**Comment by zupa-hu** [comment]
grr wrong button..

**Comment by marriog** [comment]
sorry! removed new line in recent previous update
https://github.com/marriog/learning/blob/Mutlibyte-testing/strings/Between.go
cant find diff link and runing out of time to
