### ISSUE TITLE
top, bottom

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#13]
I don't like top and bottom, a string is a linear chain of bytes, top and bottom only exists in text editors when a multi-line text is displayed. use `from, to` or something that doesn't imply 2D.

**Comment by marriog** [comment]
noted, and i have updated the naming.

**Comment by zupa-hu** [comment]
k

**Comment by zupa-hu** [comment]
Sry I didn't mean to close that one just github is painfully slow. I don't see the change.

**Comment by marriog** [comment]
I had already removed all instances of bottom or top in both files.
They were committed but im not sure when so finding the diff url for you is time tough.
Can we leave this one? i am addressing each point one at a time now with diff links for each.

**Comment by zupa-hu** [comment]
Sure, I just wanted you to feel my pain. Confirm I may close.

**Comment by marriog** [comment]
i felt your pain. you can close this now. all new issue threads have unique diff link
