### ISSUE TITLE
doc

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#14]
Where is the documentation gone? Include it before the function.

**Comment by marriog** [comment]
ok, i will add as i implement each function, unless you say otherwise.

**Comment by zupa-hu** [comment]
that would be ok except that I want you to remove the duplicate 50.go as well which will force you to do something about them

**Comment by zupa-hu** [comment]
reopening as noted in the other issue (don't close any issues just add a comment and assign them back to me)

**Comment by marriog** [comment]
I have saved the 50.go file locally to use as i update each function. Do you think its best to now go through all the files and update them instead? or you have alternative solution?

**Comment by zupa-hu** [comment]
k
