### ISSUE TITLE
Add reference

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#16]
when an issue relates to source code and you solve it with changes, can you please reference the diff so I can quickly look it up?

Like that one:
https://github.com/marriog/learning/commit/4efde02289485529db061a6451d4a20c01af0feb

**Comment by zupa-hu** [comment]
Just testing, what if I just enter this:
4efde02

**Comment by zupa-hu** [comment]
Okay you can just enter the 7 chars that identify the commit need nothing else

**Comment by marriog** [comment]
like this one:
3754392
?

**Comment by zupa-hu** [comment]
exactly, may I close?

**Comment by zupa-hu** [comment]
sry we haven't closed this yet and I expected you to already do it. That was a sync issue on my end. Sorry!

**Comment by marriog** [comment]
ok, closing.
