### ISSUE TITLE
//not needed as never ran?

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#17]
exactly, so you can remove it

**Comment by marriog** [comment]
removed by default when removing the deep code logic :)

**Comment by zupa-hu** [comment]
Please provide separate commits for separate issues for clarity. That's important if you work on a team.

Please provide diff link

**Comment by marriog** [comment]
ok, so i should work like this? :+1:
1. view issue
2. fix issue
3. push issue
4. note new commit hash and assign to you?

Happy to do this, but i have noticed that sometimes i will re-do work twice as one issue overwrites another? such as removing deep code fixes the un needed return statement.

**Comment by zupa-hu** [comment]
exactly. If there is an implicit fix, you can reference the issue #12 as well.

may I close?

**Comment by marriog** [comment]
ok, you can close

**Comment by zupa-hu** [comment]
wait a sec, how did this issue come back to life? I thought you are using version control.

**Comment by marriog** [comment]
? you can close now. not sure why it was reopened?
