### ISSUE TITLE
remove meaningless test cases

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#18]
duplicate test cases are sure not needed, and if some do not add in meaning, remove them as well. Strive to have minimum number of test cases necessary, as they always add overhead as well.

**Comment by marriog** [comment]
removed and i spotted an error in core i think
string.index(haystack, needle) will return 0 if the first letter matches but will also return 0 if the needle is "" (blank) so i updated the code to deal with this. i learned that making good test cases (varied) opens up the holes in your code big time!

**Comment by zupa-hu** [comment]
diff link pls

**Comment by marriog** [comment]
you mean you want the file before and after updating the case tests?
if so these are them:
3754392
d3eac59

**Comment by marriog** [comment]
sorry that was wrong

**Comment by zupa-hu** [comment]
the links you provide (click and try) already provide the highlighted diff, so the commit after the changes is enough

**Comment by marriog** [comment]
These are the two urls that show the test cases before and after fixing this issue:

https://github.com/marriog/learning/commit/3754392fab32e8747e4540b04615e99bdb867262

https://github.com/marriog/learning/blob/d3eac594d27258daa646ab053344ad6d04aaac46/strings/Between_test.go


from now on i will commit only one solved issue at a time

**Comment by zupa-hu** [comment]
You call them [before, after] and then you give me [after, before] references. No good.

**Comment by zupa-hu** [comment]
tell me, what additional functionality does line [27] test that the previous tests didn't?

[27]  - https://github.com/marriog/learning/blob/3754392fab32e8747e4540b04615e99bdb867262/strings/Between_test.go#L27

**Comment by zupa-hu** [comment]
same goes for lines 24 and 26 in the same file

**Comment by zupa-hu** [comment]
what if `from` is left blank `to` is not left blank?

**Comment by zupa-hu** [comment]
functionality inconsistent, if to is empty, it goes to end of string, I'd expect if from is empty, it starts from start of string and if both are empty, it goes from start to end

**Comment by zupa-hu** [comment]
what additional thing does line 36 test?

https://github.com/marriog/learning/blob/3754392fab32e8747e4540b04615e99bdb867262/strings/Between_test.go#L36

**Comment by marriog** [comment]
you're right, this is my bad. you have hawk eyes! do you have a way you systematically check?

**Comment by marriog** [comment]
removed
7e9fb6d

**Comment by zupa-hu** [comment]
sure, just multiply the possibilities. For 2 needles, each may be not found, which gives 4 variations, 1 of them is found-found, which leaves you with 3. Maybe there is no need checking notfound-notfound depending on the code, sort of optional, I don't always do if the flow of the program immediately returns if one is not found. So that leaves 2 cases, I identified both so I look at the rest what are they?

Okay, you also test empty needles her. So, a needle may be empty or not, that leaves 4 cases, one of them is notempty-notempty, which is not tested here, that leaves us with 3 test cases. In your func the not-empty checks are independent so we don't necessarily need to test empty-empty, that leaves 2 test cases required. You only have one, so I raise a new issue -> #22

**Comment by zupa-hu** [comment]
pls confirm that I may close this one

**Comment by marriog** [comment]
you can close this issue :)

**Comment by zupa-hu** [comment]
This seems to have regressed
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L24
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L35

**Comment by marriog** [comment]
01bf24e
just removed again, i am not sure how or why? perhaps it was from moving branches? i am confused why it re-appeared

**Comment by marriog** [comment]
Sorry btw, it must really annoy you :(

**Comment by zupa-hu** [comment]
I showed you an issue on the master branch, you fixed it on the Multibyte_testing branch.
As it has nothing to do with the multibyte functionality, I'd say you fixed it on the bad branch.

Please fix on the master branch.

**Comment by marriog** [comment]
noted and fixed on master branch.
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L28
