### ISSUE TITLE
reduce distance

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#19]
Reduce variable referencing distance.

By declaring testNotFound at the top, only using it at the bottom, you increase mental overhead. Move definition close to usage.

**Comment by marriog** [comment]
noted, i have now grouped the functions, data and test run together

**Comment by zupa-hu** [comment]
diff link pls

**Comment by marriog** [comment]
This shows the new layout of the grouping of data, functions and calling the functions:
https://github.com/marriog/learning/commit/3754392fab32e8747e4540b04615e99bdb867262#diff-74ee5a3d8056902abfad9b7347233c9d

**Comment by zupa-hu** [comment]
nice
