### ISSUE TITLE
FieldsThroughFunction()

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#2]
FieldsThroughFunction() is generally called Map(), and there already is a Map() in the list.

Seems I have forgotten the return []uint32. Unless you have removed it ahahah :D

**Comment by marriog** [comment]
removed function, looking for new one.
how did i miss that function return when i used the parser?!

**Comment by zupa-hu** [comment]
btw feel free to convert the project to sg. that builds

**Comment by zupa-hu** [comment]
k
