### ISSUE TITLE
remove odd newlines

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#20]
beginning and end-of-function newlines are not needed, remove

**Comment by marriog** [comment]
found and removed

**Comment by zupa-hu** [comment]
diff link pls

**Comment by marriog** [comment]
one line removed at top of this page
https://github.com/marriog/learning/commit/3754392fab32e8747e4540b04615e99bdb867262#diff-74ee5a3d8056902abfad9b7347233c9d

sorry its hard when i merge solutions, i will make sure i have a diff link (commit) for just one solution in the future

**Comment by zupa-hu** [comment]
nice!
