### ISSUE TITLE
use < instead of >

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#25]
Don't ever use `>`, always use `<` instead.

It is way easier to understand  `if a < b { ... }` than it is reading `if b > a { .. }`.
Humans by nature assume growth to the right.

**Comment by zupa-hu** [comment]
https://github.com/marriog/learning/blob/master/strings/Between.go#L27

**Comment by marriog** [comment]
noted. i remember you mentioning this to me at the flat - taken from that book of best programming tips. i will work hard to implement this.
i have updated this in a previous commit release
https://github.com/marriog/learning/blob/Mutlibyte-testing/strings/Between.go#L26
