### ISSUE TITLE
inconsistent functionality

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#26]
Handling edge cases differently makes your function harder to understand and anticipate how it works.

Here you say not providing the first needle is invalid
```go
if len(from) == 0 {
	return "", false
}
```

Here you say not providing the second needle defaults to end of string
```go
if len(to) == 0 {
	result = sandwhich
	return result, true	
}
```

**Comment by marriog** [comment]
how should i do this, this seems ok to me. not providing first needle is different providing empty second needle, so they hvae to be handled differently. how would you have written it? would you have created flagged at the top - i.e. addressed the second empty needle at the top of the function and created a flag?

**Comment by zupa-hu** [comment]
This is how I would define Between:
```go
// Between returns a substring of s that is between but excluding the strings from and to.
// When from is left empty, it defaults to start of string.
// When to is left empty, it defaults to end of string.
func Between(s, from, to string) (result string, found bool)
```

This is how you define it
```go
// Between returns a substring of s that is between but excluding the strings from and to.
// From must not be empty.
// To may be empty, it defaults to end of string.
func Between(s, from, to string) (result string, found bool)
```

I feel like you are restricting the use of Between() by forcing the user to provide `from`. It's like not being allowed to use `Substring(s string, from, to int)` with `from = 0`.

Yet you are designing this function so I'm not going to enforce this, it is up to you.

May I close?

**Comment by marriog** [comment]
ok - understood, this function was one taken from one i created years ago for parsing html pages. I always assumed there would be a from.
you can close
