### ISSUE TITLE
startOFFrom

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#27]
startOFFrom -> startOfFrom

**Comment by marriog** [comment]
noted, i have updated this in previous commit, but cant find the diff line:
here is the most recent correct one:
0aebfe9

**Comment by zupa-hu** [comment]
Nope, I mean, why are 2 capital F's in startOFFrom?

**Comment by marriog** [comment]
Sorry my eyes missed that
6a68b4a
updated

**Comment by zupa-hu** [comment]
You fixed it on the feature branch, please fix it on master.

The point of the feature branch is to only contain one feature so that it can be merged into master OR thrown away. In which case if you added important functionality on the feature branch it will be lost. Not good.

**Comment by marriog** [comment]
Ok, understood. this makes sense. learning curve of Git is growing. So when working on a feature branch ONLY update and add code related to the specific feature. I have been creating spaghetti by updating the wrong branch with the wrong issue fix.
Diff link with the (startOFFrom -> startOfFrom ) updated    : 00321e4
