### ISSUE TITLE
order

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#28]
https://github.com/marriog/learning/blob/master/strings/Between.go#L20
https://github.com/marriog/learning/blob/master/strings/Between.go#L22

The order of these statements seems wrong to me.

**Comment by zupa-hu** [comment]
As in, why call strings.Index() if you are not using the result in the next if statement?

**Comment by marriog** [comment]
ah, i see. that makes sense, its not just about the deep coded if statements but also the flow of the code.
updated: ec8a15df45

**Comment by zupa-hu** [comment]
k
