### ISSUE TITLE
double spaces

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#29]
double spaces before func

https://github.com/marriog/learning/blob/master/strings/Between_test.go#L12
https://github.com/marriog/learning/blob/master/strings/Between_test.go#L38

**Comment by marriog** [comment]
updated d3a0763
i'm sorry , this must be hard for you
you have a lot of patience!

**Comment by zupa-hu** [comment]
as explained in #27, move to master branch

**Comment by marriog** [comment]
double spaced updated on the main branch.
https://github.com/marriog/learning/commit/f259c859e31924842f456e528ac64b1113087a30#diff-74ee5a3d8056902abfad9b7347233c9dR11
