### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#3]
Shuffle() is missing the seed to be deterministic

**Comment by marriog** [comment]
I thought the string s is the seed , as the function just shuffles the characters in the string returning same sized string but with characters in different order

**Comment by zupa-hu** [comment]
what determines the order?

**Comment by marriog** [comment]
random() will be used. so no input determines the order. its a random shuffle . like a password generator

**Comment by zupa-hu** [comment]
so the function is non-deterministic, which you are not allowed to ever code

**Comment by zupa-hu** [comment]
Add a seed int64 argument you will figure it out later

**Comment by zupa-hu** [comment]
int64 not uint64

**Comment by zupa-hu** [comment]
k
