### ISSUE TITLE
bad func name

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#4]
ExplodeTwoDimArray does not what its name sais as per its comment.

Same for ExplodeThreeDimArray.

Explode is splitting not uniting.

**Comment by marriog** [comment]
renamed to PushTwoDimArray and pushed

**Comment by zupa-hu** [comment]
you haven't pushed

**Comment by zupa-hu** [comment]
print usually means writing to console. Sprint is generally used for printing to a string, or maybe Format3DArray. I hope you know what you want it to do because I don't.

**Comment by marriog** [comment]
ok cool, i took print idea from print_r from php. i like Sprint3DArray

**Comment by zupa-hu** [comment]
ok waiting for commit

**Comment by zupa-hu** [comment]
k
