### ISSUE TITLE
remove empty test files

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#8]
Sorry we must have misunderstood eachother. The point of having a _test.go file for every function separately is that you can see at a glance whether everything is tested or not just by looking at the files in a package. By pre-creating the _test.go files you immediately loose sight. Either add a `t.Error("TODO")` to all of them or remove the test files.

Also, having each empty function in a separate file means you loose the single checkpoint for seeing what else needs to get done - although looking at the files with _test.go endings helps its slower to scan with your eyes. You may optionally want to move them to a single file containing all your unimplemented ones to see them at one place. Or -but I do both- flat all empty function bodies with a `// TODO: implement` flag.

**Comment by marriog** [comment]
ok, ill remove the test files then create a test file for each new function as i go a long.

**Comment by zupa-hu** [comment]
great

**Comment by zupa-hu** [comment]
k
